name: CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy via SSH
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        # Create SSH directory and key file
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/ec2_key
        chmod 400 ~/.ssh/ec2_key

        # Run deployment commands via SSH
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key ${EC2_USER}@${EC2_HOST} << 'EOF'
          cd /home/ubuntu/fastapi-book-project
          git pull origin main
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
          sudo systemctl reload nginx
        EOF