name: CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    

      - name: Build docker image
        run: sudo docker build -t python-app .
        

      - name: Delete old container
        run: sudo docker rm -f python-app  || true

        
      - name: Run docker container
        run: sudo docker run -d -p 7001:7001 --name python-app python-app 

        
      - name: Clean up space
        run: sudo docker system prune -a -f