name: CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyngrok

    - name: Start server and ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        # Start FastAPI server in the background
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        SERVER_PID=$!

        # Set up and start ngrok tunnel
        ngrok config add-authtoken $NGROK_AUTH_TOKEN
        ngrok http 8000 > ngrok.log &
        NGROK_PID=$!

        # Wait for server to start
        sleep 5

        # Wait for ngrok tunnel to be established
        echo "Waiting for ngrok tunnel..."
        while ! curl -s http://localhost:4040/api/tunnels > /dev/null; do
          sleep 1
        done

        # Retrieve and display the public URL
        NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "Public URL: $NGROK_URL"

        # Keep the processes running for 1 hour (3600 seconds)
        sleep 3600

        # Cleanup (optional)
        kill $SERVER_PID $NGROK_PID