name: CD

on:
    pull_request:
        types:
        - closed 
        branches:
        - main   
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI server in background
      run: |
        nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &

    - name: Install ngrok
      run: pip install pyngrok

    - name: Start ngrok tunnel
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        ngrok config add-authtoken $NGROK_AUTH_TOKEN
        ngrok http 8000 > ngrok.log &
        sleep 5
        curl http://localhost:4040/api/tunnels

    - name: Display Public URL
      run: |
        curl http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
